name: Continuous integration
on: [pull_request, push]

jobs:
  nintendo_3ds:
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
      - run: wget https://github.com/devkitPro/pacman/releases/download/v1.0.2/devkitpro-pacman.amd64.deb -O /tmp/devkitpro-pacman.deb
      - run: yes | sudo dpkg -i /tmp/devkitpro-pacman.deb
      - run: yes | sudo dkp-pacman -Syu --needed devkitARM 3dstools libctru
      - run: echo ::set-env name=DEVKITPRO::/opt/devkitpro
      - run: echo ::set-env name=DEVKITARM::/opt/devkitpro/devkitARM
      - run: echo ::set-env name=PATH::$DEVKITPRO/tools/bin:$DEVKITARM/bin:$PATH
      
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -j2 PLATFORM=simulator TARGET=3ds
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-3ds.3dsx
          path: output/release/simulator/3ds/epsilon.3dsx
  android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -j2 PLATFORM=simulator TARGET=android
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-android.apk
          path: output/release/simulator/android/epsilon.apk
  n0100:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: numworks/setup-arm-toolchain@v1
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -j2 MODEL=n0100 epsilon.dfu
      - run: make -j2 MODEL=n0100 epsilon.onboarding.dfu
      - run: make -j2 MODEL=n0100 epsilon.onboarding.update.dfu
      - run: make -j2 MODEL=n0100 epsilon.onboarding.beta.dfu
      - run: make -j2 MODEL=n0100 flasher.light.dfu
      - run: make -j2 MODEL=n0100 flasher.verbose.dfu
      - run: make -j2 MODEL=n0100 binpack
      - run: cp output/release/device/n0100/binpack-n0100-`git rev-parse HEAD | head -c 7`.tgz output/release/device/n0100/binpack-n0100.tgz
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-binpack-n0100.tgz
          path: output/release/device/n0100/binpack-n0100.tgz
  n0110:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: numworks/setup-arm-toolchain@v1
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -j2 epsilon.dfu
      - run: make -j2 epsilon.onboarding.dfu
      - run: make -j2 epsilon.onboarding.update.dfu
      - run: make -j2 epsilon.onboarding.beta.dfu
      - run: make -j2 flasher.light.dfu
      - run: make -j2 flasher.verbose.dfu
      - run: make -j2 bench.ram.dfu
      - run: make -j2 bench.flash.dfu
      - run: make -j2 binpack
      - run: cp output/release/device/n0110/binpack-n0110-`git rev-parse HEAD | head -c 7`.tgz output/release/device/n0110/binpack-n0110.tgz
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-binpack-n0110.tgz
          path: output/release/device/n0110/binpack-n0110.tgz
  web:
    runs-on: ubuntu-latest
    steps:
      - uses: numworks/setup-emscripten@v2
        with:
          sdk: latest-upstream
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -j2 PLATFORM=simulator TARGET=web
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-web.zip
          path: output/release/simulator/web/epsilon.zip
  linux:
    runs-on: ubuntu-latest
    steps:
      - run: sudo apt-get install build-essential imagemagick libfreetype6-dev libjpeg-dev libpng-dev pkg-config
      - uses: actions/checkout@v1
        with:
          submodules: true
      - run: make -j2 PLATFORM=simulator
      - uses: actions/upload-artifact@master
        with:
          name: epsilon-linux.bin
          path: output/release/simulator/linux/epsilon.bin
      - run: make -j2 PLATFORM=simulator test.headless.bin
